### PR TITLE
Create a "schema" folder to create multiples schemas using the same models

### PR DESCRIPTION
**Pull request by jdnichollsc**
Hi my friend!

Can you check please? #2 

I have an issue at the moment because only one schema is imported correctly, see please http://screencast.com/t/UBIyRaX3xd

Thanks in advance, Nicholls

### CODE REVIEW

**Comment by jdnichollsc** [comment]
Sorry, It was my mistake, the new changes works good 👍

**Comment by bjrmatos** [comment]
LGTM, i'll add a test, thnks!! 😄

**Comment by jdnichollsc** [comment]
Cool my friend! Can you update the package version and update the npm module?

Thanks for all, Nicholls

**Comment by bjrmatos** [comment]
published in `v1.1.0`

**Pull request merged**
